# Generated by Django 6.0.2 on 2026-03-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_leaguemembership'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaguemembership',
            name='unique_user_per_league',
        ),
        migrations.DeleteModel(
            name='LeagueMembership',
        ),
    ]
