# Generated by Django 6.0.2 on 2026-03-01 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_league'),
        ('gameweeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='competition',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameweek',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameweek',
            name='lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['season', 'competition'], name='gameweeks_g_season__f093e8_idx'),
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['published'], name='gameweeks_g_publish_7114b3_idx'),
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['locked'], name='gameweeks_g_locked_6c8fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['lock_time'], name='gameweeks_g_lock_ti_9cfbda_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameweek',
            constraint=models.UniqueConstraint(fields=('season', 'competition', 'name'), name='unique_gameweek_per_competition_season'),
        ),
    ]
