# Generated by Django 6.0.2 on 2026-03-06 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_remove_league_unique_league_per_season_competition_and_more'),
        ('gameweeks', '0002_gameweek_competition_gameweek_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameweek',
            name='unique_gameweek_per_competition_season',
        ),
        migrations.RemoveIndex(
            model_name='gameweek',
            name='gameweeks_g_season__f093e8_idx',
        ),
        migrations.AddField(
            model_name='gameweek',
            name='competitions',
            field=models.ManyToManyField(related_name='gameweeks', to='competitions.competition'),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='league',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, related_name='gameweeks', to='competitions.league'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['league'], name='gameweeks_g_league__113ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='gameweek',
            index=models.Index(fields=['season'], name='gameweeks_g_season__ede53a_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameweek',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_gameweek_name_per_league'),
        ),
        migrations.RemoveField(
            model_name='gameweek',
            name='competition',
        ),
    ]
