# Generated by Django 6.0.2 on 2026-03-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_league'),
        ('gameweeks', '0002_gameweek_competition_gameweek_created_at_and_more'),
        ('matches', '0001_initial'),
        ('selections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('btts_success', 'BTTS Success'), ('btts_fail', 'BTTS Fail')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='gameweeks.gameweek')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='competitions.league')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'league'], name='selections__user_id_b9d632_idx'), models.Index(fields=['gameweek'], name='selections__gamewee_383726_idx'), models.Index(fields=['result_status'], name='selections__result__8aab95_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'league', 'gameweek', 'match'), name='unique_pick_per_user_match'), models.UniqueConstraint(fields=('league', 'gameweek', 'match'), name='unique_match_per_league_gameweek')],
            },
        ),
    ]
