# Generated by Django 6.0.2 on 2026-03-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('selections', '0002_pick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pick',
            name='selections__user_id_b9d632_idx',
        ),
        migrations.RemoveIndex(
            model_name='pick',
            name='selections__gamewee_383726_idx',
        ),
        migrations.RemoveIndex(
            model_name='pick',
            name='selections__result__8aab95_idx',
        ),
        migrations.AlterField(
            model_name='pick',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pick',
            name='team',
        ),
    ]
