# Generated by Django 6.0.2 on 2026-03-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_leagueinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
