# Generated by Django 6.0.2 on 2026-03-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_league_is_locked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueInvite',
        ),
    ]
