# Generated by Django 6.0.2 on 2026-03-06 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_delete_leagueinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='league',
            name='unique_league_per_season_competition',
        ),
        migrations.RemoveIndex(
            model_name='league',
            name='competition_season__b56000_idx',
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['season'], name='competition_season__098fbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('name', 'season'), name='unique_league_per_season'),
        ),
        migrations.RemoveField(
            model_name='league',
            name='competition',
        ),
    ]
